# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Santiago García Pimentel
email: santiagozky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Generic tech nerd, Adobe AEM developer, always starting and abandoing projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://santiagozky.com" # the base hostname & protocol for your site
twitter_username: sanzky
github_username:  santiagozky

# Build settings
markdown: kramdown
